insert into public.notes (slug,owner_email,title,speaker,source_kind,source_url,duration_sec,read_min,level,summary,shelf,section,tags,keywords,cover_path,html_path,visibility) values
('limuyue-46-to-90','nanhong@pumpkinvrar.com','從 46 分寫到 90 分 — AI 代理人寫作','李慕約（Generative AI 年會 策展人）','platform','',1202,11,'進階','把「請 AI 寫文章」做成流水線：指令×脈絡×工具。餵更少反而更好、刪除比補強難、多 Agent 要有可觀測儀表板。','gaiconf-2026','main',array['主題/AI寫作','主題/AI代理人','主題/脈絡工程','用途/照著做']::text[],array['AI寫作','AI代理人','脈絡工程','照著做','AI Agent（AI 代理人）','指令 Prompt','脈絡 Context','工具 Harness','反思流程','Whisper','OCR','System Prompt（系統提示）']::text[],'covers/limuyue-46-to-90.jpg','static:gaiconf-2026/limuyue-46-to-90.html','team'),
('hermes-agent-line','nanhong@pumpkinvrar.com','把 AI 小助手裝進 LINE（Hermes 接 LINE 完整教學）','網際之星開發實驗室','youtube','https://www.youtube.com/watch?v=tuVu8HuJHMc',947,10,'深入','4 步驟把會做事的 AI 接上 LINE：申請金鑰→ngrok 打通 Webhook→填設定→手機實測。含三大卡關重點。','youtube','',array['主題/AI代理人','主題/自動化','用途/照著做','關聯/自動化流程']::text[],array['AI代理人','自動化','照著做','自動化流程','AI Agent（AI 代理人）','Skill（技能）','LINE Developers','Provider（提供者）','Channel（頻道）','Messaging API','Channel Secret（頻道密鑰）','Channel Access Token（存取金鑰）']::text[],'covers/hermes-agent-line.jpg','static:youtube/hermes-agent-line.html','team'),
('andrew-wu-service-smarter','nanhong@pumpkinvrar.com','讓你的 Service 偷偷變聰明','Andrew Wu（91APP 首席架構師）','platform','https://live.gaiconf.com/learning/gaiconf2026/b9cc8820-576a-44fe-9ffb-17f7ae854067',3849,17,'深入','把 AI 放進自家產品會踩到的坑：關鍵不是挑模型而是挖出專家的 Context；安全不能靠交代 AI，要用系統邊界擋；新問題只能自己練。','gaiconf-2026','deep',array['主題/脈絡工程','主題/資安邊界','主題/團隊導入','用途/建立觀念']::text[],array['脈絡工程','資安邊界','團隊導入','建立觀念','AI Agent（AI 代理人）','LLM（大型語言模型）','Harness（外掛骨架）','Context（上下文）','Multi-Agent（多代理人）','ADK','Skill（技能包）','Tool Call（工具呼叫）']::text[],'covers/andrew-wu-service-smarter.jpg','static:gaiconf-2026/andrew-wu-service-smarter.html','team'),
('will-harness-engineering','nanhong@pumpkinvrar.com','駕馭工程必須熟知的兩三事','Will 保哥（多奇數位創意 技術總監）','platform','https://live.gaiconf.com/learning/gaiconf2026/dce17fb3-78af-484e-85e7-b048862083cd',3701,18,'深入','一個老闆的實戰與帳單：工具少即是多（15→2 快 3.5 倍）、一個工程師一天燒 3.7 億 token、公司月費 15000 美金到週費 13 美金。驗證是 Harness 的心臟。','gaiconf-2026','deep',array['主題/Harness工程','主題/成本控管','主題/團隊導入','用途/案例故事']::text[],array['Harness工程','成本控管','團隊導入','案例故事','Harness（駕馭工程）','Loop Engineering（迴圈工程）','AI Agent（AI 代理人）','Sensor（感測器／回饋）','Guide（導引）','Constraint（限制）','AGENTS.md','Skill（技能包）']::text[],'covers/will-harness-engineering.jpg','static:gaiconf-2026/will-harness-engineering.html','team'),
('ihower-harness-loop-engineering','nanhong@pumpkinvrar.com','給 Agent 開發者的 Harness + Loop Engineering','張文鈿 ihower（愛好資訊科技 AI Engineer）','platform','https://live.gaiconf.com/learning/gaiconf2026/02fac281-2e37-43b1-ba29-a981f13f7916',3660,18,'深入','AI 最常見的失敗是「沒做完卻宣稱完成」。這場把「怎麼盯住 AI」拆成四個可以插入回饋的時間點：工具內、兩次呼叫之間、每輪結束、整個重來。','gaiconf-2026','deep',array['主題/Harness工程','主題/AI代理人','用途/建立觀念']::text[],array['Harness工程','AI代理人','建立觀念','AI Agent（AI 代理人）','Harness（駕馭工程）','Loop Engineering（迴圈工程）','Turn（一輪）','Function Calling（函式呼叫）','Deep Agent','Sub-Agent（分身）','Context Window（腦容量）']::text[],'covers/ihower-harness-loop-engineering.jpg','static:gaiconf-2026/ihower-harness-loop-engineering.html','team'),
('feng-accounting-dog','nanhong@pumpkinvrar.com','從 0 開始養一隻幫公司查帳的狗！','馮元詰（薩泰爾娛樂 全端工程師）','platform','https://live.gaiconf.com/learning/gaiconf2026/a0c8b4bf-68ff-436d-b79c-729dc61cbf68',1098,12,'進階','892 天把人工報帳變成跟 AI 說一句話就查完帳。但他們不是一開始就想做 AI——統一命名才是真正的地基。','gaiconf-2026','vibe',array['主題/AI代理人','主題/自動化','主題/資料分析','用途/案例故事']::text[],array['AI代理人','自動化','資料分析','案例故事','DDD（領域驅動設計）','Google Apps Script','PostgreSQL','Redis','關聯式資料庫','AI Agent（AI 代理人）','Tool List（工具清單）','MCP']::text[],'covers/feng-accounting-dog.jpg','static:gaiconf-2026/feng-accounting-dog.html','team'),
('lin-vibe-to-production','nanhong@pumpkinvrar.com','從 Vibe Coding 到真正可以上線的產品：你還差了什麼？','林沅霖（Zeabur 創辦人）','platform','https://live.gaiconf.com/learning/gaiconf2026/942d8288-d024-4bfd-a094-f30f9506b22e',1225,14,'深入','酸民說「這就是小玩具」，其實在提醒六件事：安全、擴展、資料、上線、可觀測、可維護。每件都附可直接複製的 Prompt，共 18 組。','gaiconf-2026','vibe',array['主題/VibeCoding','主題/產品上線','用途/建立觀念']::text[],array['VibeCoding','產品上線','建立觀念','Vibe Coding','紅隊演練','API Key（金鑰）','RLS（資料列權限）','CDN','快取（Cache）','冪等性','PITR（時間點還原）']::text[],'covers/lin-vibe-to-production.jpg','static:gaiconf-2026/lin-vibe-to-production.html','team'),
('gao-vibe-or-blindbox','nanhong@pumpkinvrar.com','Vibe Coding 是寫程式還是開盲盒','高見龍（五倍學院 · Anthropic 社群大使）','platform','https://live.gaiconf.com/learning/gaiconf2026/3ca3834f-7c5e-4465-bb7f-f57c962503cc',1083,13,'進階','同一句話喊兩次結果不一樣，因為 AI 只能猜你的意圖。解法是 SDD：動手前先講清楚。附一段零安裝、可直接複製的提示詞全文。','gaiconf-2026','vibe',array['主題/VibeCoding','用途/建立觀念']::text[],array['VibeCoding','建立觀念','Vibe Coding','SDD（規格驅動開發）','Spec（規格）','Prompt（提示詞）','駕馭工程 / 迴圈工程','可打勾的任務清單','驗收條件','歸檔']::text[],'covers/gao-vibe-or-blindbox.jpg','static:gaiconf-2026/gao-vibe-or-blindbox.html','team'),
('jocelin-harness-piccollage','nanhong@pumpkinvrar.com','Harness Engineering @ PicCollage','Jocelin Ho（PicCollage 工程經理）','platform','https://live.gaiconf.com/learning/gaiconf2026/66c657e6-079b-4d4c-92b5-585be955bec7',1051,12,'進階','AI 像辛普森家庭那個天真角色——本質不壞但需要引導。三階段框架：驗證→循環優化→解放創意。工程師工作量降三成、功能產出快十倍。','gaiconf-2026','vibe',array['主題/Harness工程','主題/團隊導入','用途/案例故事']::text[],array['Harness工程','團隊導入','案例故事','Harness（馬具／駕馭工程）','Agent = LLM + Harness','確定性系統','Unit Test（單元測試）','Integration Test（整合測試）','E2E Test（端到端測試）','Regression Test（回歸測試）','Smoke Test（冒煙測試）']::text[],'covers/jocelin-harness-piccollage.jpg','static:gaiconf-2026/jocelin-harness-piccollage.html','team'),
('leo-company-mcp','nanhong@pumpkinvrar.com','當同事 AI 成癮之後，我們的下一步是什麼？','Leo（大師課業 · ShiFu AI 研究所）','platform','https://live.gaiconf.com/learning/gaiconf2026/a37c13aa-c5e0-465d-bdaf-def99ffab6e6',1001,10,'進階','沒有工程師的團隊讓全公司都會做 AI 小工具，卻發現工具變多不代表流程變順。最大的坑：資料看起來完整但數字是錯的。','gaiconf-2026','vibe',array['主題/團隊導入','主題/MCP','用途/案例故事']::text[],array['團隊導入','MCP','案例故事','Vibe Coding','Skill（技能包）','Audit（稽核紀錄）','Human in the Loop','SQL','SRT 字幕檔','Domain Knowledge（領域知識）']::text[],'covers/leo-company-mcp.jpg','static:gaiconf-2026/leo-company-mcp.html','team'),
('zheng-esun-voice-warroom','nanhong@pumpkinvrar.com','玉山的聲量戰情室','鄭東濬 TC（玉山銀行 智能金融處）','platform','https://live.gaiconf.com/learning/gaiconf2026/57077626-2a5a-4402-b5b8-181a0817864a',1218,10,'進階','搜自家銀行前五名沒有自己。找廠商要價一年三四百萬還會外流經驗，改用三隻 Agent 自己兜。神轉折：做出平台的不是工程師，是資深經理人。','gaiconf-2026','vibe',array['主題/資料分析','主題/自動化','用途/案例故事']::text[],array['資料分析','自動化','案例故事','AI Agent','Skill（技能包）','Playwright','AI Overview','Dashboard（戰情板）','Channel（通路）','Product（產品）','Competitor（競爭對手）']::text[],'covers/zheng-esun-voice-warroom.jpg','static:gaiconf-2026/zheng-esun-voice-warroom.html','team'),
('hai-ai-self-upgrade','nanhong@pumpkinvrar.com','讓 AI 自己升級自己','海總理（小海）','platform','https://live.gaiconf.com/learning/gaiconf2026/c24d4a97-6310-4161-a0f5-103a004a0bcf',973,10,'進階','把自己從 AI 迴圈裡抽掉，只要三個條件：看到結果、知道過程、能改自己。三個案例含「單次開發成本 5 美金降到 0.2 美金」。','gaiconf-2026','vibe',array['主題/AI代理人','主題/Harness工程','用途/照著做']::text[],array['AI代理人','Harness工程','照著做','Loop（迴圈）','Prompt（提示詞）','System Prompt（系統提示詞）','提示詞攻擊','LOG（執行紀錄）','API 費用','Prompt Caching（提示詞快取）','Caching Rate（快取命中率）']::text[],'covers/hai-ai-self-upgrade.jpg','static:gaiconf-2026/hai-ai-self-upgrade.html','team')
on conflict (slug) do nothing;
update public.notes set shared_at=coalesce(shared_at,created_at) where visibility='team';
